project:
  type: website
  output-dir: docs

website:
  title: "Alex [Rossell Hayes]{.semibold}"
  site-url: https://alex.rossellhayes.com
  navbar:
    right:
      - text: Articles
        href: articles.qmd
      - text: Papers
        href: academic.qmd
      - text: Packages
        href: packages.qmd
      - text: Crosswords
        href: crosswords.qmd
      - text: Media
        href: media.qmd
      - text: "{{< iconify fa6-brands github >}}"
        href: https://github.com/rossellhayes
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/alxrh.bsky.social
      - text: "{{< iconify fa6-brands mastodon >}}"
        href: https://rstats.me/@alxrh
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: https://www.linkedin.com/in/alexander-rossell-hayes/
      - text: "{{< iconify fa6-brands orcid >}}"
        href: https://orcid.org/0000-0001-9412-0457
      - text: "{{< iconify fa6-solid envelope >}}"
        href: mailto:alexander@rossellhayes.com
  page-footer: |
    Fonts are [Jost*](https://indestructibletype.com/Jost.html) by
      [indestructible type*](https://indestructibletype.com/Home.html) and
      [[Vollkorn](http://vollkorn-typeface.com/) by
      [Friedrich Althausen](http://www.grafikfritze.de/)]{.vollkorn}
format:
  html:
    theme:
      - litera
      - theme.scss
    header-includes: |
      <link rel="stylesheet" href="https://indestructibletype.com/fonts/Besley.css" type="text/css" charset="utf-8" />
      <link rel="stylesheet" href="https://indestructibletype.com/fonts/Jost.css" type="text/css" charset="utf-8" />
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Vollkorn:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
